POST http://localhost:8080/control
Content-Type: application/json
Authorization: Bearer   eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc4MDI0MDksImlhdCI6MTU5Nzc2NjQwOX0.lFNX9WnajJfsKz4ho-NsorrlLFspcG6a4WLWRCliRE4

[
  {
    "type":1,
    "name":"fish",
    "params" :
    [
      {
        "code":12,
        "set_value":144444,
        "real_value":12222
      },
      {
        "code":7,
        "set_value":-12,
        "real_value":0
      }
    ]
  },

  {
    "type":3,
    "name":"fisi",
    "params":
    [
      {
        "code":5,
        "set_value":0.11,
        "real_value":0.2
      },
      {
        "code":7,
        "set_value":-12,
        "real_value":0
      }
    ]
  }
]

###
