GET http://localhost:8080/module/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc3MTY5NjAsImlhdCI6MTU5NzY4MDk2MH0.Mc_sO6Ezr6EBPtqxgsrqj3csayg1k4RyzfcZtNQUx6s
###
POST http://localhost:8080/module
Content-Type: application/json

{
  "name": "module1",
  "moduleType": "TYPE1",
  "settings": "{'foo':'bar'}",
  "address": "12111112",
  "terrarium": "1"
}

###


