INSERT INTO PUBLIC.MODULE (ID, ADDRESS, MODULE_TYPE, NAME, TERRARIUM_ID) VALUES (1, 'fisi', '1', 'module_1', 1);
INSERT INTO PUBLIC.MODULE (ID, ADDRESS, MODULE_TYPE, NAME, TERRARIUM_ID) VALUES (2, 'fish', '2', 'module_2', 1);
INSERT INTO PUBLIC.MODULE (ID, ADDRESS, MODULE_TYPE, NAME, TERRARIUM_ID) VALUES (3, 'fici', '1', 'module_3', 2);
INSERT INTO PUBLIC.MODULE (ID, ADDRESS, MODULE_TYPE, NAME, TERRARIUM_ID) VALUES (4, 'fich', '2', 'module_4', 2);