GET http://localhost:8080/module/1
Accept: application/json
Authorization: Bearer   eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc4MDI0MDksImlhdCI6MTU5Nzc2NjQwOX0.lFNX9WnajJfsKz4ho-NsorrlLFspcG6a4WLWRCliRE4

###

POST http://localhost:8080/module
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc3NjI1ODEsImlhdCI6MTU5NzcyNjU4MX0.jVlIU8P1MhSDkWYEB9j8fFn6wJB9x7yp5lktnDTTFJ8

{
  "name": "module1",
  "moduleType": "TYPE1",
  "settings": "{'foo':'bar'}",
  "address": "12111112",
  "terrarium": "1"
}

###


