INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (1, 7, 'температура1', 1414, 1213, 1);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (2, 12, 'температура2', 1515, 1244, 2);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (3, 13, 'температура3', 2626, 1231, 3);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (4, 5, 'температура4', 2542, 2562, 4);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (5, 12, 'температура5', 1213, 1414, 1);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (6, 7, 'температура6', 1244, 1515, 2);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (7, 7, 'температура7', 1231, 2626, 3);
INSERT INTO PUBLIC.PARAMETER (ID, CODE, NAME, REAL_VALUE, SET_VALUE, MODULE_ID) VALUES (8, 12, 'температура8', 2562, 2542, 4);