GET http://localhost:8080/terrarium/1/modules
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc3NjI1ODEsImlhdCI6MTU5NzcyNjU4MX0.jVlIU8P1MhSDkWYEB9j8fFn6wJB9x7yp5lktnDTTFJ8

###
GET http://localhost:8080/terrarium
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTc3MTY5NjAsImlhdCI6MTU5NzY4MDk2MH0.Mc_sO6Ezr6EBPtqxgsrqj3csayg1k4RyzfcZtNQUx6s


###
POST http://localhost:8080/terrarium
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTYzMTQ0NTAsImlhdCI6MTU5NjI3ODQ1MH0.nuKR45jbfg3Nr2usvzDUBmlIBFU74DbnYuLT-_kzlsM

{
  "code": "12",
  "user": "1",
  "modules":[
    "123"
  ]
}

###
