GET http://localhost:8080/terrarium/1/modules
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTYzMTQ0NTAsImlhdCI6MTU5NjI3ODQ1MH0.nuKR45jbfg3Nr2usvzDUBmlIBFU74DbnYuLT-_kzlsM

###
GET http://localhost:8080/terrarium
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTYzMTQ0NTAsImlhdCI6MTU5NjI3ODQ1MH0.nuKR45jbfg3Nr2usvzDUBmlIBFU74DbnYuLT-_kzlsM


###
POST http://localhost:8080/terrarium
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW0iLCJleHAiOjE1OTYzMTQ0NTAsImlhdCI6MTU5NjI3ODQ1MH0.nuKR45jbfg3Nr2usvzDUBmlIBFU74DbnYuLT-_kzlsM

{
  "code": "12",
  "user": "1",
  "modules":[
    "123"
  ]
}

###
